### ISSUE TITLE
starting lingon on custom port shows inaccurate error message?

### ISSUE THREAD

**Issue by davidxia** [spotify/lingon#115]
```
lingon server -p 5700 [or any other custom port]

[ Lingon ] Working directory: /home/dxia/systemz-deployment-history
[ Lingon ] http server listening on: http://0.0.0.0:5700
[ Lingon ] Livereload is listening on port 35729
[ Lingon ] [Error] Port 5700 is already in use, lingon server could not start!
[ Lingon ] [Info] Try with a different one: lingon server -p <PORT>
```

But when I request the page, it works!

```
[ Lingon ] source/index.html -> 0.0.0.0:5700/index.html
[ Lingon ] source/all.less -> 0.0.0.0:5700/all.css
[ Lingon ] source/all.js -> 0.0.0.0:5700/all.js
```

**Comment by philipvonbargen** [comment]
Hm that is weird indeed. I tried reproducing it just now on Mac and Ubuntu but it always worked. What version of lingon (`lingon version`) and node (`node --version`) are you using and on what OS?

**Comment by davidxia** [comment]
```
awsuse1-heliosagent-a2.shared.cloud.spotify.net% lingon version
[ Lingon CLI ] Lingon CLI version: 0.2.2
[ Lingon ] Lingon version: 2.1.4
awsuse1-heliosagent-a2% node --version
v0.10.25
```

**Comment by philipvonbargen** [comment]
I can still not reproduce this behavior. I tried it on two Spoticloud machines (one with Ubuntu packaged node, one with nodenv installed node) and both times I could start in server mode on custom ports. Do you possibly have anything else running on the ports you tried?

**Comment by javoire** [comment]
5700 sounds an awful lot like apollo.... :P

**Comment by davidxia** [comment]
@javoire I figured it out. You can repro by starting lingon and then in another process run lingon with another port. Both will work, but the second thinks that whatever port you specified even if it's free is not.

**Comment by davidxia** [comment]
Wow thanks for tracking this down.

On Friday, January 9, 2015, Jonatan Dahl <notifications@github.com> wrote:

> Ah! And the error bubbles up through the pipes and appears the be the
> lingon port, since it's the same error type (allthough different origins
> but lingon doesn't sense that)
>
> El viernes, 9 de enero de 2015, Philip von Bargen <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> escribió:
>
> > I just checked the project you are running in the background on that
> host
> > and I think I know what's wrong: it has the live-reload plugin included
> > which is also starting a server of it's own on port 35729. I suspect
> that
> > the error message is from that plugin instead since that port is already
> in
> > use when starting the second process.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/spotify/lingon/issues/115#issuecomment-69311350>.
> >
>
>
> --
> *Jonatan Dahl <http://www.linkedin.com/pub/jonatan-dahl/31/127/813>*
> +46 (0) 70 450 39 16
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/lingon/issues/115#issuecomment-69311894>.
>


-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by javoire** [comment]
@philipvonbargen, you think its possible for lingon to detect where the error comes from? to clarify the error message. Though I guess livereload should catch the error rather.

**Comment by philipvonbargen** [comment]
@javoire: The exception unfortunately does not give any info besides that it is of type `EADDRINUSE`, not even which port or file it might be related to.

**Comment by javoire** [comment]
Yea suspected so
