### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory

### ISSUE THREAD

**Issue by javoire** [spotify/lingon#126]
```
[ Lingon ] source/index.html -> build/index.html
[ Lingon ] source/all.less -> 0.0.0.0:5678/all.css
[ Lingon ] source/all.js -> 0.0.0.0:5678/all.js
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
```

has happened like 3 times in the last couple of months, so it's super rare, might not even be lingon related (probably not)

**Comment by philipvonbargen** [comment]
@javoire: This seems to be a Node.js error when trying to load really big files or exceed e.g. the integer range in an array. If you come across this again can you show me on a specific project/example.

I'll close this until then.
